export RDP_HOST="mypc.contoso.xyz"
export DOMAIN_USERNAME="username"
export DOMAIN_PW="Sup3rSecureP@ssw0rd546"
export DOMAIN="contoso.xyz"
export BW_CLIENTID="user.9999999999"
export BW_CLIENTSECRET="xyzxyzXYZXYZ"
